// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuKiFAZbL1DbYNEGo_YOKYnVnAI4pqvsM',
    appId: '1:450598201491:web:792340cac9f00f38d1c566',
    messagingSenderId: '450598201491',
    projectId: 'busway-78e31',
    authDomain: 'busway-78e31.firebaseapp.com',
    databaseURL: 'https://busway-78e31-default-rtdb.firebaseio.com',
    storageBucket: 'busway-78e31.appspot.com',
    measurementId: 'G-B44Z51HX2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF5GiTG97JpFPRMF1sCbrgmsw9V4qbPk0',
    appId: '1:450598201491:android:e770a8176643f30cd1c566',
    messagingSenderId: '450598201491',
    projectId: 'busway-78e31',
    databaseURL: 'https://busway-78e31-default-rtdb.firebaseio.com',
    storageBucket: 'busway-78e31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0HagiZuUEEtIMUbfyt-GSlxcAVm3jPcg',
    appId: '1:450598201491:ios:3bf52bf31d6f64bcd1c566',
    messagingSenderId: '450598201491',
    projectId: 'busway-78e31',
    databaseURL: 'https://busway-78e31-default-rtdb.firebaseio.com',
    storageBucket: 'busway-78e31.appspot.com',
    iosClientId: '450598201491-ctvj6bgpsrdaut4sl8e20vegdl45vuqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.busway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0HagiZuUEEtIMUbfyt-GSlxcAVm3jPcg',
    appId: '1:450598201491:ios:3bf52bf31d6f64bcd1c566',
    messagingSenderId: '450598201491',
    projectId: 'busway-78e31',
    databaseURL: 'https://busway-78e31-default-rtdb.firebaseio.com',
    storageBucket: 'busway-78e31.appspot.com',
    iosClientId: '450598201491-ctvj6bgpsrdaut4sl8e20vegdl45vuqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.busway',
  );
}
